# Generated by Django 5.0.7 on 2024-07-11 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardcomment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.card'),
        ),
        migrations.AddField(
            model_name='cardfile',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.card'),
        ),
        migrations.AddField(
            model_name='cardimage',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.card'),
        ),
    ]
