# Generated by Django 5.0.7 on 2024-07-11 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCommentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.cardcomment')),
            ],
        ),
        migrations.CreateModel(
            name='CardCommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to='')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.cardcomment')),
            ],
        ),
    ]
