# Generated by Django 5.0.7 on 2024-07-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_cardcommentfile_cardcommentimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardcomment',
            old_name='author',
            new_name='user',
        ),
    ]
