# Generated by Django 5.0.7 on 2024-07-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_rename_author_cardcomment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardcomment',
            old_name='user',
            new_name='author',
        ),
    ]
