# Generated by Django 5.0.7 on 2024-07-26 20:08

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_cardcomment_related_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cat1', [('subcat1', 'aaaaa'), ('subcat2', 'bbbbb')]), ('cat2', [('subcat3', 'ccccc')])], default='ccccc', max_length=9),
            preserve_default=False,
        ),
    ]
