# Generated by Django 5.0.7 on 2024-07-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_card_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='num_of_resp',
        ),
        migrations.RemoveField(
            model_name='card',
            name='showing_price',
        ),
        migrations.RemoveField(
            model_name='card',
            name='tags',
        ),
    ]
