# Generated by Django 5.0.7 on 2024-07-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_remove_card_num_of_resp_remove_card_showing_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='properties',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
