# Generated by Django 5.0.7 on 2024-07-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usercomment_usercommentfile_usercommentimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contacts',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tags',
            field=models.JSONField(null=True),
        ),
    ]
