# Generated by Django 5.0.7 on 2024-07-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_contacts_alter_customuser_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFiles',
            new_name='UserFile',
        ),
    ]
