# Generated by Django 5.0.7 on 2024-07-14 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favourites',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
