# Generated by Django 5.0.7 on 2024-07-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_favourites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='author',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='userfile',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='userimage',
            old_name='user',
            new_name='owner',
        ),
    ]
