# Generated by Django 5.0.7 on 2024-07-15 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_author_usercomment_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommentfile',
            name='owner',
            field=models.ForeignKey(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercommentimage',
            name='owner',
            field=models.ForeignKey(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
