# Generated by Django 5.0.7 on 2024-07-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercommentfile',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='usercommentimage',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='usercommentfile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='usercommentimage',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='favourites',
        ),
        migrations.DeleteModel(
            name='UserComment',
        ),
        migrations.DeleteModel(
            name='UserCommentFile',
        ),
        migrations.DeleteModel(
            name='UserCommentImage',
        ),
        migrations.DeleteModel(
            name='UserFile',
        ),
    ]
