# Generated by Django 5.0.7 on 2024-07-18 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_usercommentfile_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
    ]
