# Generated by Django 5.0.7 on 2024-07-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_userimage_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rating',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
