# Generated by Django 5.0.7 on 2024-07-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='inn',
            field=models.CharField(max_length=10),
        ),
    ]
