# Generated by Django 5.0.7 on 2024-07-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customuser_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tags',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
